# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

# services 定义容器列表
services:
  consignment-cli:
    build: ./consignment-cli
    depends_on:
      - consignment-service
    environment:
      MICRO_REGISTRY: "mdns"
  user-cli:
    build: ./user-cli
    depends_on:
      - user-service
    environment:
      MICRO_REGISTRY: "mdns"
  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    depends_on:
      - vessel-service
      - datastore
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    depends_on:
      - datastore
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      SQL_DRV: "postgres"
      SQL_DSN: "host=database port=5432 user=postgres dbname=ship password=password sslmode=disable"
    depends_on:
      - database
  datastore:
    image: mongo
    ports:
      - 27017:27017
  database:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: "password"
  api-service:
    image: microhq/micro
    ports:
      - 8080:8080
      - 8082:8082
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_API_NAMESPACE: "go.micro.srv"
      MICRO_API_HANDLER: "rpc"
    depends_on: 
      - consignment-service
      - vessel-service
      - user-service
      